export const apiUrl = 'https://api.coinmarketcap.com/v1/ticker/';

export const coinDescriptions = [
  {
    "rank": 1,
    "symbol": "BTC",
    "name": "Bitcoin",
    "country": "USA/Global",
    "description": "",
    "Tag1": "Mineable",
    "Tag2": "Decentralised",
    "Tag3": "blockchain",
    "Tag4": "proof-of-work consensus",
    "Tag5": "peer-to-peer transactions",
    "Tag6": "SHA256 algorithm",
    "Tag7": "fixed supply of tokens",
    "Tag8": "pseudonymous",
    "Tag9": "1 MB block size",
    "Tag10": "Satoshi Nakamoto",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 2,
    "symbol": "ETH",
    "name": "Ethereum",
    "country": "USA",
    "description": "This is decentralized cryptocurrency that allows users to be able build decentralized applications and also handle smart contracts",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "DApps",
    "Tag6": "SHA 256 algorithm",
    "Tag7": "infinite supply",
    "Tag8": "Known",
    "Tag9": "1 MB",
    "Tag10": "Vitalik Buterin",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 3,
    "symbol": "XRP",
    "name": "Ripple",
    "country": "USA",
    "description": "This is a decentralized payment settlement and real time gross remittance platform",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Real time payment protocol",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "2MB",
    "Tag10": "Chris Larsen",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 4,
    "symbol": "BCH",
    "name": "Bitcoin Cash",
    "country": "Global",
    "description": "This is a hard fork of the Bitcoin network and it was forked out of a disagreement that ensued between community members",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Peer to Peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "8 MB",
    "Tag10": "Community Members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 5,
    "symbol": "EOS",
    "name": "EOS",
    "country": "Global",
    "description": "This is a decentralized platform that seeks to use smart contracts to create a platform for the development of decentralized applications.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "DApps and Smart contracts",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Brendan Blumer",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 6,
    "symbol": "LTC",
    "name": "Litecoin",
    "country": "Global",
    "description": "This is a decentralized peer to peer platform that has been described as an advanced and enhanced version of the Bitcoin network",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Peer to peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "Known",
    "Tag9": "1 MB",
    "Tag10": "Charlie Lee",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 7,
    "symbol": "ADA",
    "name": "Cardano",
    "country": "Hong Kong/ Global",
    "description": "This is a platform that runs the ADA cryptocurrency",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "distributed protocol",
    "Tag6": "",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Charles Hoskinson",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 8,
    "symbol": "XLM",
    "name": "Stellar",
    "country": "Global",
    "description": "This is a decentralized open source platform for the exchange of valuable items",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Proof of stake",
    "Tag5": "value exchange protocol",
    "Tag6": "",
    "Tag7": "Fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jed McCaleb",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 9,
    "symbol": "TRX",
    "name": "TRON",
    "country": "Global",
    "description": "This is a blockchain based platform that seeks to create an entertainment content driven platform",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Content driven platform",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Justin Sun",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 10,
    "symbol": "MIOTA",
    "name": "IOTA",
    "country": "Global",
    "description": "This a blockchain based platform that was created specially for improving internet of things",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "IoT",
    "Tag6": "Scrypt",
    "Tag7": "fixed token supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Team members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 11,
    "symbol": "NEO",
    "name": "NEO",
    "country": "China/ Global",
    "description": "This is a network that seeks to build a scalable environment for decentralized applications",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "DApps",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "OnChain Company",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 12,
    "symbol": "USDT",
    "name": "Tether",
    "country": "US",
    "description": "This is a cryptocurrency that its developers' claim is backed by the US Dollar",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Brock Pierce",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 13,
    "symbol": "DASH",
    "name": "Dash",
    "country": "Global",
    "description": "This is an anonymous cryptocurrency that seeks to improve the efficiency level of the payment industry",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Evan Duffield",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 14,
    "symbol": "XMR",
    "name": "Monero",
    "country": "Global",
    "description": "This is a cryptocurrency platform that places its focus on decentralization as well as the privacy of its users",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Anonymous token",
    "Tag6": "CryptoNight",
    "Tag7": "fixed supply",
    "Tag8": "Known",
    "Tag9": "1 MB",
    "Tag10": "Nicolas Van Saberhagen",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 15,
    "symbol": "XEM",
    "name": "NEM",
    "country": "Global",
    "description": "This is a cryptocurrency platform that seeks to focus on the distribution of models as well as improving the blockchain technology",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Proof of Importance",
    "Tag5": "peer to peer",
    "Tag6": "Eigentrust ++",
    "Tag7": "fixed supply",
    "Tag8": "Pseudonymous",
    "Tag9": "1 MB",
    "Tag10": "UtopianFuture",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 16,
    "symbol": "VEN",
    "name": "VeChain",
    "country": "China",
    "description": "This is a cryptocurrency platform that focuses on improving the supply chain management, smart contracts and financial services.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Supply chain management",
    "Tag6": "",
    "Tag7": "fixed supply",
    "Tag8": "unknown",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 17,
    "symbol": "ETC",
    "name": "Ethereum Classic",
    "country": "US",
    "description": "This is a hard fork of the Ethereum network and it seeks to feature smart contracts",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "DApps",
    "Tag6": "Scrypt",
    "Tag7": "Fixed supply",
    "Tag8": "Known",
    "Tag9": "1 MB",
    "Tag10": "Ethereum community members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 18,
    "symbol": "BNB",
    "name": "Binance Coin",
    "country": "Global",
    "description": "This is the native coin of the crypto exchange Binance and it is used to make payments for all activities carried out on the Binance exchange",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Exchange function",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Changpeng Zhao",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 19,
    "symbol": "QTUM",
    "name": "Qtum",
    "country": "China",
    "description": "A platform that seeks to connect the Ethereum network and the Bitcoin network",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Virtual Machine and Smart contracts",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Qtum Foundation established by Patrick Dai",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 20,
    "symbol": "BCN",
    "name": "Bytecoin",
    "country": "Global",
    "description": "This is a cryptocurrency platform that was designed for payment settlement as well as offering users anonymous transactions",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Payment settlement",
    "Tag6": "CryptoNote",
    "Tag7": "fixed supply",
    "Tag8": "Pseudonymous",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "PACIFIC_SKYLINE",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 21,
    "symbol": "OMG",
    "name": "OmiseGO",
    "country": "US",
    "description": "This cryptocurrency seeks to improve the general efficiency of traditional financial institution and it is tagged as \"banker of the unbanked\".",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "financial services",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Vitalik Buterin, Gavin Wood and Joseph Poon",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 22,
    "symbol": "ZEC",
    "name": "Zcash",
    "country": "Global",
    "description": "This is a cryptocurrency platform that seeks to make use of cryptography to hide the transaction details on its network",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Anonymous transactions",
    "Tag6": "ZK-SNARKS",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Zooko Wilcox-O Healm",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 23,
    "symbol": "ICX",
    "name": "ICON",
    "country": "South Korea",
    "description": "This is a cryptocurrency platform that seeks to redefine decentralization by creating new worlds by connecting various communities",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Redefining blockchain",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Dayli Financial Group",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 24,
    "symbol": "LSK",
    "name": "Lisk",
    "country": "US",
    "description": "This is a platform that seeks to change the way the blockchain technology functions and it seeks to make it more accessible",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Delegated proof of stake",
    "Tag5": "Make the blockchain technology more accessible",
    "Tag6": "",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Oliver Beddows and Max Kordek",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 25,
    "symbol": "ZIL",
    "name": "Zilliqa",
    "country": "Global",
    "description": "This is the only blockchain platform that allows Sharding. This means that its blockchain can be split into smaller parts",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Proof of Work",
    "Tag5": "DApps",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Xinsho Dung",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 26,
    "symbol": "ONT",
    "name": "Ontology",
    "country": "China",
    "description": "This is a platform that seeks to ensure that users without prior knowledge of cryptocurrencies and blockchain can be able to make use of their platform.",
    "Tag1": "minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "OnChain Company",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 27,
    "symbol": "AE",
    "name": "Aeternity",
    "country": "Global",
    "description": "This is a new network that was developed for increasing the efficiency of decentralized applications.",
    "Tag1": "Not minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "DApps",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Yanislav Manahov",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 28,
    "symbol": "BTG",
    "name": "Bitcoin Gold",
    "country": "USA/ Global",
    "description": "This is another hard fork of Bitcoin that was created to restore or ensure that users could mine with Graphic Processing Units",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "Equihash",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Bitcoin community members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 29,
    "symbol": "DCR",
    "name": "Decred",
    "country": "Global",
    "description": "This is a cryptocurrency platform that seeks to focus mainly on open governance, sustainable development as well as community input",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work and proof of stake",
    "Tag5": "Open governance system",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jake Yocom-Piatt",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 30,
    "symbol": "ZRX",
    "name": "0x",
    "country": "Global",
    "description": "This is a blockchain based platform that seeks to facilitate the  operations of decentralized exchanges and how they handle Ethereum based tokens",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "DApps",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Team members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 31,
    "symbol": "BTM",
    "name": "Bytom",
    "country": "Global",
    "description": "This is a blockchain platform that acts as a link between specialized blockchains and generalized blockchains.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Tensority",
    "Tag5": "intermediary",
    "Tag6": "AI",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Community members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 32,
    "symbol": "STEEM",
    "name": "Steem",
    "country": "US",
    "description": "This is a platform that seeks to incentivize the creation of contents as well as attaching value to a particular content",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Proof of work",
    "Tag5": "Reward platform",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Developed by the Steemit platform",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 33,
    "symbol": "XVG",
    "name": "Verge",
    "country": "Global",
    "description": "This is a cryptocurrency platform that seeks to offer users the opportunity to carry out anonymous transactions by hiding the location and Internet Protocol (IP) address of their users.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Privacy coin",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Soroosh P",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 34,
    "symbol": "NANO",
    "name": "Nano",
    "country": "Global",
    "description": "This platform seeks to become what Bitcoin is not; that is a more efficient and better alternative to fiat or physical currencies",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "peer to peer",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 35,
    "symbol": "BTS",
    "name": "BitShares",
    "country": "USA",
    "description": "This is a decentralized open source platform that seeks to create or facilitate payment systems by creating an exchange.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "financial services",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Developed by the Bitshares community members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 36,
    "symbol": "SC",
    "name": "Siacoin",
    "country": "Global",
    "description": "This is a decentralized platform that offers cloud storage services. It seeks to rent out storage spaces to users for rewards",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Reward platform",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Luke Champine and David Vorick",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 37,
    "symbol": "PPT",
    "name": "Populous",
    "country": "Global",
    "description": "This platform has been described as the only Ethereum enabled crypto platform that deals with trade and finance invoice..",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "POW",
    "Tag5": "trade and invoice",
    "Tag6": "",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Stephen Williams",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 38,
    "symbol": "RHOC",
    "name": "RChain",
    "country": "Global",
    "description": "This is a blockchain based project that seeks to implement or build a new blockchain that would allow users to be able to build applications that would be used on a larger scale.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Implementation of new blockchain",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "unknown",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 39,
    "symbol": "WAN",
    "name": "Wanchain",
    "country": "Global",
    "description": "This platform seeks to build a distributed infrastructure that would of digital tokens that will form a modern framework",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Value exchange between blockchains",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jang Lu",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 40,
    "symbol": "BTCP",
    "name": "Bitcoin Private",
    "country": "Global",
    "description": "This is a P2P (Peer to peer) platform that seeks to ensure that the transaction information of users, receivers as well as the amount sent is kept private",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Peer to Peer",
    "Tag6": "Equihash",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Community members, Jacob Brutman, Lon Layton",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 41,
    "symbol": "MKR",
    "name": "Maker",
    "country": "Global",
    "description": "This platform seeks to solve the problem of volatility that has plagued cryptocurrencies since their inception.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Problem solving",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 42,
    "symbol": "GNT",
    "name": "Golem",
    "country": "USA",
    "description": "This platform seeks to decentralize central processing powers.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Decentralize CPU's",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 43,
    "symbol": "BCD",
    "name": "Bitcoin Diamond",
    "country": "USA",
    "description": "This is a hard fork of the Bitcoin network and it seeks to offer users the opportunity to carry out anonymous transactions",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "",
    "Tag9": "1 MB",
    "Tag10": "Bitcoin community members",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 44,
    "symbol": "STRAT",
    "name": "Stratis",
    "country": "Global",
    "description": "This is a BAAS (Blockchain As A Service) platform that was developed to help businesses to be able to make use of the blockchain technology in various industries.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "BAAS",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Chris Trew",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 45,
    "symbol": "WAVES",
    "name": "Waves",
    "country": "Global",
    "description": "This is a decentralized platform that has the main of generating tokens for the platform. It measn that users will be able to launch their own cryptocurrencies",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Launch cryptocurrencies",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Sasha Ivanov",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 46,
    "symbol": "REP",
    "name": "Augur",
    "country": "USA",
    "description": "This is a cryptocurrency platform that was developed to reward users who are able to make accurate predictions on future events",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Reward system",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jack Paterson",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 47,
    "symbol": "DOGE",
    "name": "Dogecoin",
    "country": "USA",
    "description": "This is a meme themed cryptocurrency and like Bitcoin, it seeks to ensure that its users can carry out cheap and fast transactions.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Joke currency",
    "Tag6": "SHA 256",
    "Tag7": "Infinite coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Billy Markus and Jackson Palmer",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 48,
    "symbol": "XIN",
    "name": "Mixin",
    "country": "Global",
    "description": "This is a platform that was created to ensure that everyone has a platform where they can carry out cheap and fast transactions.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work algorithm",
    "Tag5": "Payment settlement",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "unknown",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 49,
    "symbol": "WICC",
    "name": "WaykiChain",
    "country": "China",
    "description": "This is a platform that handles smart contracts as well as support Turing device.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Smart contracts",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Sun YongGang",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 50,
    "symbol": "WTC",
    "name": "Waltonchain",
    "country": "Global",
    "description": "This platform seeks to combine Internet of Things with RFID to create an efficient management system for all supply chain companies.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake and trust",
    "Tag5": "Reward system",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Do Sanghyuk",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 51,
    "symbol": "DGB",
    "name": "DigiByte",
    "country": "Global",
    "description": "This platform seeks to create a new future for digital currencies by combining new innovations and certain problem solving skills",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "5 Algorithms",
    "Tag5": "blockchain technology",
    "Tag6": "",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jared Tate",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 52,
    "symbol": "IOST",
    "name": "IOST",
    "country": "Global",
    "description": "This platform seeks to create a new infrastructure that would help all service providers.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Rias Resistance Random Distribution",
    "Tag5": "Infrastructural development",
    "Tag6": "",
    "Tag7": "Fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Terrence Wang",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 53,
    "symbol": "SNT",
    "name": "Status",
    "country": "Global",
    "description": "This is a decentralized platform that seeks to create a management system that is similar to the WeChat messenger.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Ethereum based",
    "Tag6": "Scrypt",
    "Tag7": "Fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Carl Bennet and Hope Jarrad",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 54,
    "symbol": "AION",
    "name": "Aion",
    "country": "Global",
    "description": "This is a blockchain 3.0 platform that seeks to offer blockchain interoperability",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "blockchain interoperability",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Nuco Matthew",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 55,
    "symbol": "HSR",
    "name": "Hshare",
    "country": "Global",
    "description": "This is a token that would allow users to be able to transfer other tokens securely across blockchains",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "POW and POS",
    "Tag5": "exchange value",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Dallas Brooks",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 56,
    "symbol": "NAS",
    "name": "Nebulas",
    "country": "Global",
    "description": "This platform seeks to create a platform where users would be able to track and view all decentralized applications built",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "DApps",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Hitters Xu",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 57,
    "symbol": "LRC",
    "name": "Loopring",
    "country": "Global",
    "description": "This is a platform that was built in the Ethereum network and it seeks to allow its users to be able to trade digital assets across various exchanges",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "value exchange",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "",
    "Tag9": "1 MB",
    "Tag10": "Daniel Wang",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 58,
    "symbol": "BAT",
    "name": "Basic Attenti...",
    "country": "USA",
    "description": "This is the native cryptocurrency of the Brave Browser which seeks to hide ads and also reward ad creators and publishers",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Browser reward token",
    "Tag6": "Scrypt",
    "Tag7": "infinite supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Brendan Eich",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 59,
    "symbol": "DGD",
    "name": "DigixDAO",
    "country": "Global",
    "description": "This is a platform that seeks to back each token with a bar of gold",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of provenance",
    "Tag5": "Gold platform",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Kai Cheng",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 60,
    "symbol": "CMT",
    "name": "CyberMiles",
    "country": "USA",
    "description": "This is a platform that is still undergoing development and seeks to revolutionize how markets work",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "marketplace",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Dr. Lucas Lu",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 61,
    "symbol": "KMD",
    "name": "Komodo",
    "country": "Global",
    "description": "This is platform that has been compared to the Dash network and Bitcoin, the difference being that it has additional features.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin",
    "Tag8": "pseudonymous",
    "Tag9": "1 MB",
    "Tag10": "JL777 and Pbca26",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 62,
    "symbol": "ARDR",
    "name": "Ardor",
    "country": "Global",
    "description": "This is the first BAAS that was developed for business",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "BAAS platform",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jelurida Company",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 63,
    "symbol": "ELF",
    "name": "aelf",
    "country": "Global",
    "description": "This platform seeks to create two channels; side chains as well as a very unique governance system",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Side chain",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Ma Haobo",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 64,
    "symbol": "ARK",
    "name": "Ark",
    "country": "France",
    "description": "This is a platform that seeks to connect blockchains to ensure that they transact freely",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "peer to peer",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Francois Xavier Thoreens",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 65,
    "symbol": "PIVX",
    "name": "PIVX",
    "country": "Global",
    "description": "This is one of the best privacy token and it makes use of the proof of stake algorithm",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Privacy token",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "Anonymous",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 66,
    "symbol": "POLY",
    "name": "Polymath",
    "country": "USA",
    "description": "This platform seeks to open up the blockchain technology to various securities",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Blockchain technology",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Chris and Trevor Housser",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 67,
    "symbol": "LOOM",
    "name": "Loom Network",
    "country": "Global",
    "description": "Not just being a new cryptocurrency, this platform seeks to solve some of the problems facing the Ethereum network",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Ethereum based",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "unknown",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 68,
    "symbol": "DCN",
    "name": "Dentacoin",
    "country": "Global",
    "description": "This is the first platform that has been developed for the dental industry and it seeks to enhance the efficiency level",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Dental industry",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "unknown",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 69,
    "symbol": "GXS",
    "name": "GXChain",
    "country": "Global",
    "description": "This is a decentralized platform that supports the issuance of applications and digital tokens",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "value exchange",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Minqiang Huang",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 70,
    "symbol": "MONA",
    "name": "MonaCoin",
    "country": "Japan",
    "description": "This is a platform that have been described by its developers as the most active and friendly community in Japan",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Lyra2Rev2",
    "Tag5": "meme themed coin",
    "Tag6": "",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Monacoin company",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 71,
    "symbol": "BNT",
    "name": "Bancor",
    "country": "Global",
    "description": "This is a platform that allows it users to convert one token for another like exchanges do",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Value exchange",
    "Tag6": "Scrypt",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 72,
    "symbol": "CTXC",
    "name": "Cortex",
    "country": "Global",
    "description": "This platform seeks to create an Artificial Intelligence autonomous system that makes use of the blockchain technology.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "AI platform",
    "Tag6": "Scrypt",
    "Tag7": "infinite coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Ziqi Chen",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 73,
    "symbol": "MYB",
    "name": "MyBit Token",
    "country": "Global",
    "description": "This is a platform that seeks to ensure the tokenization of revenues that is built on Ethereum's network",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Revenue tokenization platform",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Ian Worall",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 74,
    "symbol": "ELA",
    "name": "Elastos",
    "country": "Global",
    "description": "This is a platform that seeks to create a new kind of internet and users would be able to trade and make money from digital assets",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Digital asset platform",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "",
    "Tag9": "1 MB",
    "Tag10": "Rong Chen",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 75,
    "symbol": "MAID",
    "name": "MaidSafeCoin",
    "country": "UK",
    "description": "This is a platform that seeks to provide general security as well as privacy to all users",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "privacy coin",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "David Irvine",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 76,
    "symbol": "SKY",
    "name": "Skycoin",
    "country": "Global",
    "description": "This is a next generation innovative blockchain based project that has been developing for the past seven years.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Obeslik algorithm",
    "Tag5": "peer to peer",
    "Tag6": "web",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Huowu Chen and Synth",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 77,
    "symbol": "GAS",
    "name": "Gas",
    "country": "China",
    "description": "This is the cryptocurrency that is used to fuel the NRO platform. As the name implies, it is the gas that empowers and runs the network",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Gas",
    "Tag6": "Scrypt",
    "Tag7": "Infinite supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "OnChain Company",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 78,
    "symbol": "RDD",
    "name": "ReddCoin",
    "country": "Global",
    "description": "This has been referred to as the social media token as well as a P2P platform that allows you send and receive funds easily.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "POSV",
    "Tag5": "Peer to Peer",
    "Tag6": "",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Leonard Simonse and John Nash",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 79,
    "symbol": "CNX",
    "name": "Cryptonex",
    "country": "Global",
    "description": "This token we developed for the main purpose of offering users the opportunity to easily change or convert any fiat currency for any token of their choice",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Digital exchange platform",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 80,
    "symbol": "HT",
    "name": "Huobi Token",
    "country": "US",
    "description": "This is the native coin of the Huobi. Pro group and the value of this token depends immensely on the performance of the parent company",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "ERC-20 token",
    "Tag6": "SHA 256",
    "Tag7": "fixed supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Huobi.Pro",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 81,
    "symbol": "SYS",
    "name": "Syscoin",
    "country": "Global",
    "description": "This is a distributed ledger, a global network, an altoin that it at the same time tradeable",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Distributed ledger",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Blockchain Foundry",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 82,
    "symbol": "QASH",
    "name": "QASH",
    "country": "Global",
    "description": "This is the native cryptocurrency of the QUOINNE platform that seeks to solve the problem of liquidity",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Liquidity problem",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Mike Kayamori",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 83,
    "symbol": "MITH",
    "name": "Mithril",
    "country": "Global",
    "description": "This is a reward platform that gives users token for interacting with others on the network.",
    "Tag1": "Social Mining",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Reward system",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jeffrey Huang",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 84,
    "symbol": "FSN",
    "name": "Fusion",
    "country": "Global",
    "description": "This is a platform that seeks to allow off-chain data support, internet of value and smart contracts for multiple tokens",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Hybrid Hierarchical Consensus Mechanism",
    "Tag5": "Smart contracts",
    "Tag6": "",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Dejun Qian, Dr. Jiangang Wu and Noam Cohen",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 85,
    "symbol": "ETHOS",
    "name": "Ethos",
    "country": "USA",
    "description": "This is a platform that seeks to make the crypto market more accessible to the average trader by providing needed tools for the acceleration and mass adoption of the blockchain technology",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Marketplace",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Shingo Lavine",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 86,
    "symbol": "KNC",
    "name": "Kyber Network",
    "country": "Global",
    "description": "This is a new platform that would seek to enable all investors to be able to invest easily in ICO's",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "ICO platform",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "Unknown",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 87,
    "symbol": "FUN",
    "name": "FunFair",
    "country": "USA",
    "description": "This is a gaming platform that makes use of the Ethereum blockchain to ensure fairness and also seeks to change the face of casino games",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Gaming platform",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Jez",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 88,
    "symbol": "VERI",
    "name": "Veritaseum",
    "country": "Global",
    "description": "This is a platform that seeks to offer investors the opportunity to not only manage but also exchange values with other users",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "Scrypt",
    "Tag7": "infinite coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Reggie Middleton",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 89,
    "symbol": "ETN",
    "name": "Electroneum",
    "country": "Global",
    "description": "This is a platform that seeks to solve any location problem by offering users a mobile app that can be accessed by any individual anywhere.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Richard Ellis",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 90,
    "symbol": "SUB",
    "name": "Substratum",
    "country": "Global",
    "description": "This is a P2P platform that was developed to address all issues involving data security, censorship and the general internet interference.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "peer to peer",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Justin Tabb",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 91,
    "symbol": "CENNZ",
    "name": "Centrality",
    "country": "New Zealand",
    "description": "This is a platform that has partnered with various top brands to create a marketplace for the sell and purchase of applications",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Applications",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Aaron McDonalds",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 92,
    "symbol": "NXS",
    "name": "Nexus",
    "country": "US",
    "description": "Unlike most platforms, the Nexus seeks to improve on the blockchain technology so that it would be able in the future to develop 3D chains",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Blockchain",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Colin Cantrell",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 93,
    "symbol": "RLC",
    "name": "iExec RLC",
    "country": "Global",
    "description": "This platform makes use of the Siacoin cloud storage and the Golem supercomputing to ensure that it offers advanced features to users",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "Super computing",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Giles Fedak",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 94,
    "symbol": "DRGN",
    "name": "Dragonchain",
    "country": "USA",
    "description": "This is a platform that was created for use in business. It has been referred to as the most friendly platform that has even been developed.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "Proof of stake",
    "Tag5": "Business use",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Joe Roets",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 95,
    "symbol": "ENG",
    "name": "Enigma",
    "country": "USA",
    "description": "This is a platform that seeks to solve the problem that has been facing blockchain. Which is privacy and scalability and this platform was developed after a research was conducted at the MIT",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "blockchain problem",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Guy Zyskind",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 96,
    "symbol": "NULS",
    "name": "Nuls",
    "country": "Global",
    "description": "This is a customizable blockchain platform that seeks to ensure that more people are able to make use of the technology",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of credit",
    "Tag5": "blockchain technology",
    "Tag6": "Modules",
    "Tag7": "fixed coin supply",
    "Tag8": "unknown",
    "Tag9": "",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 97,
    "symbol": "SOC",
    "name": "All Sports",
    "country": "Global",
    "description": "This platform seeks to connect various sport predictions companies by providing them with the necessary Internet Protocol (IP) and smart contracts that would increase their efficiency level",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "sports coin",
    "Tag6": "Scrypt",
    "Tag7": "fixed coin supply",
    "Tag8": "unknown",
    "Tag9": "",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 98,
    "symbol": "XZC",
    "name": "ZCoin",
    "country": "Global",
    "description": "This is a cryptocurrency platform that seeks to ensure that its users would be able to carry out anonymous and private transactions.",
    "Tag1": "Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of work",
    "Tag5": "Privacy coin",
    "Tag6": "SHA 256",
    "Tag7": "fixed coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Dr. Matthew Green",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 99,
    "symbol": "HOT",
    "name": "Holo",
    "country": "Global",
    "description": "This platform seeks to ensure that users are able to build and launch decentralized applications on their platform. They also want to change the paradigm of blockchains.",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "DApps",
    "Tag6": "Scrypt",
    "Tag7": "Unannounced coin supply",
    "Tag8": "unknown",
    "Tag9": "1 MB",
    "Tag10": "",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  },
  {
    "rank": 100,
    "symbol": "KIN",
    "name": "Kin",
    "country": "USA",
    "description": "This is the native coin of the KIK messenger and it it used to facilitate the network",
    "Tag1": "Not Minable",
    "Tag2": "Decentralized",
    "Tag3": "blockchain",
    "Tag4": "proof of stake",
    "Tag5": "GAS",
    "Tag6": "Scrypt",
    "Tag7": "infinite coin supply",
    "Tag8": "known",
    "Tag9": "1 MB",
    "Tag10": "Ted Livingston",
    "Tag11": "",
    "Tag12": "",
    "Tag13": "",
    "Tag14": "",
    "Tag15": "",
    "Tag16": "",
    "Tag17": "",
    "Tag18": ""
  }
]
